- name: mongo
  hosts: mongo
  become: yes
  tasks:
  - name: include role to install and configure MongoDB
    ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

  - name: installing
    ansible.builtin.yum:
      name: mongodb-org
      state: present
  - name: start and enabled
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: enable remote connections to mongodb
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  -  name: restart
     ansible.builtin.restart:
      name: mongod
      state: restarted
      enabled: yes