- name: mysql
  host: mysql
  become: yes
  tasks:
  - name: installing
    ansible.builtin.get_url: https://rpms.remirepo.net/enterprise/remi-release-8.rpm

  - name: module
    ansible.builtin.command: yum module disable mysql -y

  - name: installing
    ansible.builtin.yum:
      name: redis
      state: present

  - name: replace
    ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"

  - name: redis start and enable
    ansible.builtin.service:
      name: redis
      state: installed
      enabled: yes

  - name: change default root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

  
      